import { db } from "./client.js";
import { insertWord } from "./wordsRepo.js";

const SEED_WORDS: Array<{ text: string; category: "noun" | "phrase"; weight: 1 | 2 | 3 | 4 | 5 }> = [
  { text: "вода", category: "noun", weight: 1 },
  { text: "стол", category: "noun", weight: 1 },
  { text: "дерево", category: "noun", weight: 1 },
  { text: "телефон", category: "noun", weight: 2 },
  { text: "холодильник", category: "noun", weight: 2 },
  { text: "белая ворона", category: "phrase", weight: 2 },
  { text: "фотосинтез", category: "noun", weight: 3 },
  { text: "куриная слепота", category: "phrase", weight: 3 },
  { text: "меридиан", category: "noun", weight: 3 },
  { text: "аллегория", category: "noun", weight: 4 },
  { text: "аберрация", category: "noun", weight: 4 },
  { text: "яблоко раздора", category: "phrase", weight: 4 },
  { text: "дисперсия", category: "noun", weight: 5 },
  { text: "аннексия", category: "noun", weight: 5 },
  { text: "прокрастинация", category: "noun", weight: 5 },
  { text: "гордиев узел", category: "phrase", weight: 5 },
  { text: "хлеб", category: "noun", weight: 1 },
  { text: "рюкзак", category: "noun", weight: 2 },

  // weight 1
  { text: "кошка", category: "noun", weight: 1 },
  { text: "собака", category: "noun", weight: 1 },
  { text: "машина", category: "noun", weight: 1 },
  { text: "дом", category: "noun", weight: 1 },
  { text: "окно", category: "noun", weight: 1 },
  { text: "дверь", category: "noun", weight: 1 },
  { text: "книга", category: "noun", weight: 1 },
  { text: "ручка", category: "noun", weight: 1 },
  { text: "чашка", category: "noun", weight: 1 },
  { text: "ложка", category: "noun", weight: 1 },
  { text: "вилка", category: "noun", weight: 1 },
  { text: "тарелка", category: "noun", weight: 1 },
  { text: "стул", category: "noun", weight: 1 },
  { text: "диван", category: "noun", weight: 1 },
  { text: "лампа", category: "noun", weight: 1 },
  { text: "зеркало", category: "noun", weight: 1 },
  { text: "часы", category: "noun", weight: 1 },
  { text: "сумка", category: "noun", weight: 1 },
  { text: "шапка", category: "noun", weight: 1 },
  { text: "куртка", category: "noun", weight: 1 },
  { text: "солнце", category: "noun", weight: 1 },
  { text: "дождь", category: "noun", weight: 1 },

  // weight 2
  { text: "велосипед", category: "noun", weight: 2 },
  { text: "самолёт", category: "noun", weight: 2 },
  { text: "поезд", category: "noun", weight: 2 },
  { text: "автобус", category: "noun", weight: 2 },
  { text: "компьютер", category: "noun", weight: 2 },
  { text: "клавиатура", category: "noun", weight: 2 },
  { text: "наушники", category: "noun", weight: 2 },
  { text: "зонт", category: "noun", weight: 2 },
  { text: "перчатки", category: "noun", weight: 2 },
  { text: "ботинки", category: "noun", weight: 2 },
  { text: "будильник", category: "noun", weight: 2 },
  { text: "чайник", category: "noun", weight: 2 },
  { text: "микроволновка", category: "noun", weight: 2 },
  { text: "пылесос", category: "noun", weight: 2 },
  { text: "гитара", category: "noun", weight: 2 },
  { text: "барабан", category: "noun", weight: 2 },
  { text: "скрипка", category: "noun", weight: 2 },
  { text: "картина", category: "noun", weight: 2 },
  { text: "ваза", category: "noun", weight: 2 },
  { text: "ковёр", category: "noun", weight: 2 },
  { text: "светофор", category: "noun", weight: 2 },
  { text: "аптечка", category: "noun", weight: 2 },

  // weight 3
  { text: "атмосфера", category: "noun", weight: 3 },
  { text: "гравитация", category: "noun", weight: 3 },
  { text: "экосистема", category: "noun", weight: 3 },
  { text: "вулкан", category: "noun", weight: 3 },
  { text: "ледник", category: "noun", weight: 3 },
  { text: "созвездие", category: "noun", weight: 3 },
  { text: "метеорит", category: "noun", weight: 3 },
  { text: "гейзер", category: "noun", weight: 3 },
  { text: "коралл", category: "noun", weight: 3 },
  { text: "айсберг", category: "noun", weight: 3 },
  { text: "как две капли воды", category: "phrase", weight: 3 },
  { text: "бить баклуши", category: "phrase", weight: 3 },
  { text: "зарубить на носу", category: "phrase", weight: 3 },
  { text: "витать в облаках", category: "phrase", weight: 3 },
  { text: "водить за нос", category: "phrase", weight: 3 },
  { text: "сесть в лужу", category: "phrase", weight: 3 },
  { text: "задеть за живое", category: "phrase", weight: 3 },
  { text: "шевелить мозгами", category: "phrase", weight: 3 },
  { text: "тянуть кота за хвост", category: "phrase", weight: 3 },
  { text: "дать дуба", category: "phrase", weight: 3 },
  { text: "мозговой штурм", category: "phrase", weight: 3 },
  { text: "кот в мешке", category: "phrase", weight: 3 },

  // weight 4
  { text: "катализатор", category: "noun", weight: 4 },
  { text: "парадигма", category: "noun", weight: 4 },
  { text: "симбиоз", category: "noun", weight: 4 },
  { text: "энтропия", category: "noun", weight: 4 },
  { text: "амбивалентность", category: "noun", weight: 4 },
  { text: "олигархия", category: "noun", weight: 4 },
  { text: "гегемония", category: "noun", weight: 4 },
  { text: "ретроспектива", category: "noun", weight: 4 },
  { text: "конъюнктура", category: "noun", weight: 4 },
  { text: "реминисценция", category: "noun", weight: 4 },
  { text: "панацея", category: "noun", weight: 4 },
  { text: "плацебо", category: "noun", weight: 4 },
  { text: "ахиллесова пята", category: "phrase", weight: 4 },
  { text: "дамоклов меч", category: "phrase", weight: 4 },
  { text: "ящик пандоры", category: "phrase", weight: 4 },
  { text: "крокодиловы слёзы", category: "phrase", weight: 4 },
  { text: "вавилонская башня", category: "phrase", weight: 4 },
  { text: "авгиевы конюшни", category: "phrase", weight: 4 },
  { text: "троянский конь", category: "phrase", weight: 4 },
  { text: "сизифов труд", category: "phrase", weight: 4 },
  { text: "прокрустово ложе", category: "phrase", weight: 4 },
  { text: "стереотип", category: "noun", weight: 4 },

  // weight 5
  { text: "квинтэссенция", category: "noun", weight: 5 },
  { text: "эквилибристика", category: "noun", weight: 5 },
  { text: "эсхатология", category: "noun", weight: 5 },
  { text: "солипсизм", category: "noun", weight: 5 },
  { text: "апофения", category: "noun", weight: 5 },
  { text: "синестезия", category: "noun", weight: 5 },
  { text: "палимпсест", category: "noun", weight: 5 },
  { text: "гелиоцентризм", category: "noun", weight: 5 },
  { text: "антропоморфизм", category: "noun", weight: 5 },
  { text: "детерминизм", category: "noun", weight: 5 },
  { text: "мимикрия", category: "noun", weight: 5 },
  { text: "трансцендентность", category: "noun", weight: 5 },
  { text: "буриданов осёл", category: "phrase", weight: 5 },
  { text: "пиррова победа", category: "phrase", weight: 5 },
  { text: "филькина грамота", category: "phrase", weight: 5 },
  { text: "тришкин кафтан", category: "phrase", weight: 5 },
  { text: "лебединая песня", category: "phrase", weight: 5 },
  { text: "манна небесная", category: "phrase", weight: 5 },
  { text: "эзопов язык", category: "phrase", weight: 5 },
  { text: "яблоко от яблони", category: "phrase", weight: 5 },
  { text: "кануть в лету", category: "phrase", weight: 5 },
  { text: "нить ариадны", category: "phrase", weight: 5 },
];

function main() {
  db.exec("DELETE FROM words");
  for (const word of SEED_WORDS) {
    insertWord(word);
  }
  console.log(`Seeded ${SEED_WORDS.length} words.`);
}

main();
